#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python manage.py migrate

python manage.py import_user_submissions /app/resources/scores.json

echo "from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.filter(username='admin').exists() or User.objects.create_superuser('admin', '', 'password')" | python manage.py shell

python manage.py runserver 0.0.0.0:8000
